config/routes.rb
Events::Application.routes.draw do
  resources :events, only: [:create, :new]

  resource :sessions, only: [:create, :new]
  resource :identity, only: [:create, :new]

  get 'log_out' => 'sessions#destroy', as: :log_out
  get 'log_in' => 'sessions#new', as: :log_in
  get 'sign_up' => 'identities#new', as: :sign_up

  root to: 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :identity

  validates_presence_of :identity_id, :name, :description,
    :start_date, :end_date, :location

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    identity = where(email: email).first

    if identity && identity.password_hash == BCrypt::Engine.hash_secret(password, identity.password_salt)
      identity
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_identity, :identity_logged?

private
  def current_identity
    @current_identity ||= Identity.find(session[:identity_id]) if session[:identity_id]
  end

  def current_identity=(identity_id)
    session[:identity_id] = identity_id
  end

  def identity_logged?
    !current_identity.nil?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new event_params
    @event.identity = current_identity

    if @event.save
      redirect_to root_url, notice: t('.success')
    else
      render :new
    end
  end

private
  def event_params
    params.require(:event).permit :name, :description, :start_date, :end_date, :location, :organizer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController

  def new
    @identity = Identity.new
  end

  def create
    @identity = Identity.new identity_params

    if @identity.save
      self.current_identity = @identity.id
      redirect_to root_url, notice: t('.sign_up')
    else
      render :new
    end
  end

private
  def identity_params
    params.require(:identity).permit :email, :password, :password_confirmation
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    identity = Identity.authenticate params[:email], params[:password]

    if identity
      self.current_identity = identity.id
      return redirect_to root_url, notice: t('.logged_in')
    end
    flash.now.alert = t('.invalid_credentials')
    render :new
  end

  def destroy
    self.current_identity = nil
    redirect_to root_url, notice: t('.logged_out')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def has_errors(model, field)
    'error' if model.errors[field].any?
  end

  def field_errors(model, field)
    if model.errors[field].any?
      return content_tag :span, class: 'help-inline' do
        model.errors[field].join(', ')
      end
    end
  end

  def form_errors(model)
    if model.errors.any?
      content_tag :div, class: 'alert alert-error' do
        content = content_tag :strong, t(:invalid_form)
        content << content_tag(:span, t(:correct_errors))
      end
    end
  end
end

app/views/events/new.html.haml
%h2=t('.create_event')
%p=t('.create_message')

= form_errors(@event)

= form_for @event, html: { class: 'form-horizontal'} do |form|
  .control-group{class: has_errors(@event, :name)}
    = form.label :name, class: 'control-label'
    .controls
      = form.text_field :name, class: 'input-large'
      = field_errors(@event, :name)

  .control-group{class: has_errors(@event, :description)}
    = form.label :description, class: 'control-label'
    .controls
      = form.text_area :description, class: 'input-large'
      = field_errors(@event, :description)

  .control-group.date{class: has_errors(@event, :start_date)}
    = form.label :start_date, class: 'control-label'
    .controls
      = form.datetime_select :start_date, class: 'input-large'
      = field_errors(@event, :start_date)

  .control-group.date{class: has_errors(@event, :end_date)}
    = form.label :end_date, class: 'control-label'
    .controls
      = form.datetime_select :end_date, class: 'input-large'
      = field_errors(@event, :end_date)

  .control-group{class: has_errors(@event, :location)}
    = form.label :location, class: 'control-label'
    .controls
      = form.text_area :location, class: 'input-large'
      = field_errors(@event, :location)

  .control-group
    = form.label :organizer, class: 'control-label'
    .controls
      = form.text_field :organizer, class: 'input-large'

  .form-actions
    = form.submit t('.create'), class: 'btn btn-primary'
    = link_to t('.cancel'), root_path, class: 'btn'

app/views/home/index.html.haml
.hero-unit
  %h1= t '.welcome_message'
  %p= t '.introduction'

.row

app/views/identities/new.html.haml
%h2=t('.create_account')
%p=t('.create_message')

= form_errors(@identity)

= form_for @identity, url: identity_path, html: { class: 'form-horizontal' }  do |form|
  .control-group{class: has_errors(@identity, :email) }
    = form.label :email, class: 'control-label'
    .controls
      = form.text_field :email, class: 'input-large'
      = field_errors(@identity, :email)

  .control-group{class: has_errors(@identity, :password) }
    = form.label :password, class: 'control-label'
    .controls
      = form.password_field :password, class: 'input-large'
      = field_errors(@identity, :password)

  .control-group{class: has_errors(@identity, :password_confirmation) }
    = form.label :password_confirmation, class: 'control-label'
    .controls
      = form.password_field :password_confirmation, class: 'input-large'
      = field_errors(@identity, :password_confirmation)

  .form-actions
    = form.submit t('.create'), class: 'btn btn-primary'
    = link_to t('.cancel'), root_path, class: 'btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Events
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render partial: 'shared/nav_bar'

    .container.content
      = yield

app/views/shared/_nav_bar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to t('.app_name'), root_path, class: 'brand'
      .navbar-content
        %ul.nav
          %li.active
            = link_to t('.home'), root_path
          - if identity_logged?
            %li
              = link_to t('.create_event'), new_event_path
      .navbar-content
        %ul.nav.pull-right
          -if identity_logged?
            %li=link_to t('.hello', user: current_identity.email)
            %li= link_to t('.log_out'), log_out_path
          - else
            %li=link_to t('.sign_up'), sign_up_path
            %li= link_to t('.log_in'), log_in_path